version = 1

# Configuration files
[[annotations]]
path = [
    ".gitattributes",
    ".github/actions/setup-ccache/SHA256SUMS-*.txt",
    ".github/agents/agentic-workflows.agent.md",
    ".github/aw/actions-lock.json",
    ".github/dependabot.yml",
    ".github/pull_request_template.md",
    ".github/workflows/*.lock.yml",
    ".gitignore",
    ".python-version",
    ".release-please-manifest.json",
    "buildspec.json",
    "CHANGELOG.md",
    "CMakePresets.json",
    "data/config.json",
    "data/manifest.json",
    "release-please-config.json",
    "requirements-build.txt",
    "scripts/windows/*",
    "src/exported_symbols_linux.map",
    "src/exported_symbols_macos.txt",
    "src/exported_symbols_windows.def",
    "vcpkg-configuration.json",
    "vcpkg.json",
    "vcpkg-configuration.json",
]
SPDX-FileCopyrightText = [
    "2018-2026 OBS Project and its contributors",
]
SPDX-License-Identifier = "CC0-1.0"

# Locale files (reuse tool has some bug around reading not-ASCII files)
[[annotations]]
path = [
    "data/locale/*.ini"
]
SPDX-FileCopyrightText = [
]
SPDX-License-Identifier = "CC0-1.0"
