version = 1

# Configuration files
[[annotations]]
path = [
    ".gitignore",
    ".ncurc.json",
    ".node-version",
    ".prettierrc",
    "astro.config.mjs",
    "package-lock.json",
    "package.json",
    "tsconfig.json",
]
SPDX-FileCopyrightText = [
]
SPDX-License-Identifier = "CC0-1.0"
