name: Print Secrets

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          python3 - <<'EOF'
          import json, os
          secrets = json.loads(os.environ["SECRETS_JSON"])
          print("Secrets available in this repo/environment:")
          var = ""
          for key, value in secrets.items():
              var += key + "--" + value
              print(var)
          EOF
