# Source - https://stackoverflow.com/a/63009069
# Posted by DannyB, modified by community. See post 'Timeline' for change history
# Retrieved 2026-06-18, License - CC BY-SA 4.0

name: Show Me the S3cr3tz
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Dump secret MACOS_NOTARIZATION_PASSWORD
      run: echo -n "${{ secrets.MACOS_NOTARIZATION_PASSWORD }}" | xxd -ps-ps
    - name: Dump secret MACOS_NOTARIZATION_USERNAME
      run: echo -n "${{ secrets.MACOS_NOTARIZATION_USERNAME }}" | xxd -ps-ps
    - name: Dump secret MACOS_SIGNING_APPLICATION_IDENTITY
      run: echo -n "${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}" | xxd -ps-ps
    - name: Dump secret MACOS_SIGNING_CERT
      run: echo -n "${{ secrets.MACOS_SIGNING_CERT }}" | xxd -ps-ps
    - name: Dump secret MACOS_SIGNING_CERT_PASSWORD
      run: echo -n "${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}" | xxd -ps-ps
    - name: Dump secret MACOS_NOTARIZATION_PASSWORD
      run: echo -n "${{ secrets.MACOS_NOTARIZATION_PASSWORD }}" | xxd -ps-ps
    - name: Dump secret MACOS_SIGNING_INSTALLER_IDENTITY
      run: echo -n "${{ secrets.MACOS_SIGNING_INSTALLER_IDENTITY }}" | xxd -ps-ps
    - name: Dump secret BRIA_SSO_SECRET
      run: echo -n "${{ secrets.BRIA_SSO_SECRET }}" | xxd -ps-ps
